server:
  name: "elastic.pl4.dev"
  port: 5601
  host: "0.0.0.0"

  basePath: "/kibana"
  rewriteBasePath: true
  publicBaseUrl: "/kibana"
  ssl:
    enabled: false

path:
  data: /data

pid:
  file: /run/kibana/kibana.pid

i18n:
  locale: "en"

elasticsearch:
  hosts: ["https://elastic.pl4.dev:443"]
  username: "kibana_system"
  password: "pass"
  pingTimeout: 1500
  requestTimeout: 30000
  maxSockets: 1024
  compression: true
  requestHeadersWhitelist: [ authorization ]
  ssl:
    verificationMode: full

logging:
  appenders:
    stdout:
      type: console
  root:
    level: info
    appenders:
      - stdout
