name: Willow Application Server
slug: willow-was
description: Run a willow application service
url: https://github.com/toverainc/willow-application-server

image: flapperdeflipper/addon-willow-was
version: 2023.11.05.08

init: false
boot: auto
startup: services

hassio_api: true
hassio_role: default
host_network: true

arch:
- amd64

ingress: true
ingress_port: 8502
ingress_entry: admin

ports:
  8501/tcp: 8501
  8502/tcp: 8502

ports_description:
  8501/tcp: "Willow WAS UI listen port"
  8502/tcp: "Willow WAS API listen port"

map:
- ssl
- share:rw
