name: Willow Application Server
slug: willow-was
description: Run a willow application service
url: https://github.com/toverainc/willow-application-server

image: flapperdeflipper/addon-willow-was
version: 2023.11.05.02

services:
- mqtt:need

init: false
boot: auto
startup: services

uart: false

hassio_api: true
hassio_role: default
host_network: false

arch:
- amd64

ingress: true

ports:
  8501/tcp: 8501
  8502/tcp: 8502

ports_description:
  8501/tcp: "Willow WAS UI listen port"
  8502/tcp: "Willow WAS API listen port"

map:
- ssl
- share:rw

options:
  firmware_dir: /share/willow-was
  firmware_dest: /app/storage/ota/local
  log_level: INFO

schema:
  firmware_dir: str?
  firmware_dest: str?
  log_level: list(info|debug|error)
